version: '2.1'
services:
  openvpn:
    cap_add:
      - NET_ADMIN
    build: .
    container_name: openvpn
    ports:
      - "1194:1194/tcp"
    restart: always
    volumes:
     - ./data:/etc/openvpn